### PR TITLE
Issue64

### LINKED ISSUE #64: Design a New Logo
We can do better than a question mark :laughing:

### PR DESCRIPTION
**Pull request by Mohammed-JS-Khan**
Fixes #64 
Desktop View:
image

Mobile View:
image

### CODE REVIEW

**Review by esteeroramy — COMMENTED** [review]
Can we move the CSS into login.css (if it doesn't exist create it)

**Review by mehtadarshan1 — APPROVED** [review]
New logo is sick!

**Review by ahmedqarmout2 — APPROVED** [review]
Move the CSS into its own file plz

**Review by Mohamed-A-Mohamed — APPROVED** [review]
Aside from moving css, looks good

**Review by esteeroramy — APPROVED** [review]

**Pull request merged**
