### PR TITLE
Added student view of the hint after answering a question incorrectly…

### PR DESCRIPTION
**Pull request by esteeroramy**
Hint shows after the student answers the question incorrectly once.

### CODE REVIEW

**Review by Mohammed-JS-Khan — APPROVED** [review]
Fix seems good.

**Review by Mohamed-A-Mohamed — APPROVED** [review]
Looks good to me.

**Review by ahmedqarmout2 — APPROVED** [review]

**Review by larryyueli — APPROVED** [review]
Looks good.

**Comment by esteeroramy** [comment]
This is a comment to test slack integration

**Comment by esteeroramy** [comment]
Testing comment on slack

**Pull request merged**
