### PR TITLE
Added the chart library

### PR DESCRIPTION
**Pull request by esteeroramy**

### CODE REVIEW

**Comment by ahmedqarmout2** [comment]
I found an easier way, I will make a PR soon. Please take a look at how I added and used the materialize library

**Review by Mohamed-A-Mohamed — DISMISSED** [review]
Not trying to be mean, but I don't think a PR was necessary for adding a library :laughing:  Rejecting for now as I'm want to see Ahmed's easier solution.

Ahmed: we need this file, but Ramy and I were discussing an easier way to include the libaray without include the entire file. The easier way is to include in the package file, and refer to the lib directory when try to access this library.

Ahmed: This is my fault, I should've done more research before rushing into including the file. My bad

**Comment by esteeroramy** [comment]
The location of the file has been changed. It is now under `public/lib`

**Review by ahmedqarmout2 — APPROVED** [review]

**Review by Mohammed-JS-Khan — APPROVED** [review]
Looks good to me

**Pull request merged**
